Repository virtapi/marmoset, pull requests merged in 2020-06, with the labels that each got.

#110 fix lint errors and prospector dependency for py3.8
  .prospector.yaml
  marmoset/cli/pxe_parser.py
  marmoset/imagecatalog/catalog.py
  marmoset/pxe/exceptions.py
  marmoset/validation.py
  requirements.txt
  setup.py
  tox.ini
Labels: bug, enhancement

#111 fix flask_restful imports
  marmoset/webserver/dhcp.py
  marmoset/webserver/imagecatalog.py
  marmoset/webserver/installimage.py
  marmoset/webserver/installstatus.py
  marmoset/webserver/pxe.py
  marmoset/webserver/vm.py
  setup.py
Labels: bug

#112 Allow `bin.bz2` as image extension
  marmoset/imagecatalog/catalog.py
Labels: enhancement

#115 Installimage: Add support for internal/minimal attributes
  marmoset/imagecatalog/image.py
Labels: enhancement
